# Site settings
title: "Ammar Daskin-System Programming in Unix"

course_semester: "Spring 2025"

baseurl: "" 
url: "http://adaskin.github.io/" 



# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jemoji
google_analytics: G-TK95NJTFFL

